### ISSUE TITLE
Implement lower_footer from Amazon landing page

### ISSUE THREAD

**Issue by shashank-priyadarshi** [Ecommerce-Clone/Core-UI#18]
![image](https://user-images.githubusercontent.com/57692808/216509913-09b1482e-dda9-49c9-8d2a-4990c93b3713.png)

**Comment by fakeaman** [comment]
![image](https://user-images.githubusercontent.com/65224722/217254172-9e498aca-d72b-43c8-97d9-bbb9304520f6.png)
