### ISSUE TITLE
Create top_header clone of Amazon landing page

### ISSUE THREAD

**Issue by shashank-priyadarshi** [Ecommerce-Clone/Core-UI#2]
![image](https://user-images.githubusercontent.com/57692808/215402807-0d3d07fc-3da0-441e-88e9-73d12bb96656.png)

**Comment by shashank-priyadarshi** [comment]
- Amazon logo with prime subscription status
- Location according to last order delivery
- Search bar
-- All categories
-- Search box
-- Search option
- Language & Country dropdown
- Logged In account modal
- Return & Orders
- Cart

**Comment by palash4263** [comment]
https://github.com/palash4263/amazon_landing_page/tree/main

**Comment by shashank-priyadarshi** [comment]
Thanks for the effort @palash4263 , however we are using Angular 13 and SASS to create a clone on the whole Amazon landing page.
If you want to contribute, you can create a new issue in this repo for the element you see fit, and create your own branch and start contributing.
You can base your branch on the dev branch of this repo to avoid issues while creating PRs.

**Comment by shashank-priyadarshi** [comment]
![image](https://user-images.githubusercontent.com/57692808/215321227-3019ede3-1996-411c-ae49-84534499c981.png)
@fakeaman please review.
